spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mat_dev
    username: mat_dev_user
    password: mateusz123
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true